# Generated by Django 4.1.13 on 2023-12-11 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='files/orders', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip'])])),
                ('type', models.CharField(choices=[('1', 'Information'), ('2', 'Implement')], default='1', max_length=12)),
                ('to_role', models.CharField(choices=[('1', 'Super Admin'), ('2', 'Region Admin'), ('3', 'District Admin'), ('4', 'Imam'), ('5', 'Sub Imam')], default='4', max_length=18)),
                ('from_date', models.DateField(blank=True)),
                ('to_date', models.DateField(blank=True)),
                ('voice', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('file_bool', models.BooleanField(default=False)),
                ('to_district', models.ManyToManyField(blank=True, related_name='orders', to='common.districts')),
                ('to_imams', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('to_region', models.ManyToManyField(related_name='orders', to='common.regions')),
            ],
            options={
                'verbose_name': 'Buyruq ',
                'verbose_name_plural': 'Buyruqlar ',
            },
        ),
        migrations.CreateModel(
            name='OrdersEmployeeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(blank=True, upload_to='images/ordersresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('video', models.FileField(blank=True, upload_to='videos/ordersresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('voice', models.FileField(blank=True, upload_to='voices/ordersresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='files/ordersresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip'])])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderemployeeresult', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderemployeeresult', to='orders.orders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersEmployeeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('seen', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderemployeeread', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderemployeeread', to='orders.orders')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
