# Generated by Django 4.1.13 on 2023-12-12 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionsemployeeresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionemployeeresult', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directionsemployeeread',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionemployeeread', to='orders.directions'),
        ),
        migrations.AddField(
            model_name='directionsemployeeread',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionemployeeread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directions',
            name='to_district',
            field=models.ManyToManyField(blank=True, related_name='direction', to='common.districts'),
        ),
        migrations.AddField(
            model_name='directions',
            name='to_imams',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directions',
            name='to_region',
            field=models.ManyToManyField(related_name='direction', to='common.regions'),
        ),
    ]
