# Generated by Django 4.1.13 on 2023-12-12 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='file',
            field=models.FileField(upload_to='files/direction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'ppt'])]),
        ),
    ]
