# Generated by Django 4.1.13 on 2023-12-13 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_directions_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directions',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='directions',
            name='from_role',
            field=models.CharField(choices=[('1', 'Super Admin'), ('2', 'Region Admin'), ('3', 'District Admin')], default='4', max_length=18),
        ),
        migrations.AddField(
            model_name='directionsemployeeread',
            name='state',
            field=models.CharField(choices=[('1', 'Unseen'), ('2', 'Accepted'), ('3', 'Done')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_role',
            field=models.CharField(choices=[('2', 'Region Admin'), ('3', 'District Admin'), ('4', 'Imam'), ('5', 'Sub Imam')], default='4', max_length=18),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='file',
            field=models.FileField(blank=True, upload_to='files/directionresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'ppt'])]),
        ),
    ]
