# Generated by Django 4.1.13 on 2023-12-13 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_type_directions_types_directions_from_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='file',
            field=models.FileField(upload_to='files/direction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='file',
            field=models.FileField(blank=True, upload_to='files/directionresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])]),
        ),
    ]
