# Generated by Django 4.1.13 on 2023-12-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_directions_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionsemployeeread',
            name='requirement',
            field=models.BooleanField(default=False),
        ),
    ]
