# Generated by Django 4.1.13 on 2023-12-13 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_directionsemployeeread_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionsemployeeresult',
            name='image',
        ),
        migrations.RemoveField(
            model_name='directionsemployeeresult',
            name='video',
        ),
        migrations.CreateModel(
            name='ResultVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('video', models.FileField(blank=True, upload_to='videos/directionresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.directionsemployeeresult', verbose_name='result_image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(blank=True, upload_to='images/directionsresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.directionsemployeeresult', verbose_name='result_image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
