# Generated by Django 4.1.13 on 2023-12-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_directions_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionsemployeeread',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='resultimages',
            name='result',
        ),
        migrations.RemoveField(
            model_name='resultvideos',
            name='result',
        ),
        migrations.AddField(
            model_name='directionsemployeeresult',
            name='images',
            field=models.ManyToManyField(blank=True, to='orders.resultimages'),
        ),
        migrations.AddField(
            model_name='directionsemployeeresult',
            name='videos',
            field=models.ManyToManyField(blank=True, to='orders.resultvideos'),
        ),
    ]
