# Generated by Django 4.1.13 on 2023-12-19 10:13

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_directionsemployeeread_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('file', models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/directionresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='directionsemployeeresult',
            name='file',
        ),
        migrations.AlterField(
            model_name='directions',
            name='file',
            field=models.FileField(help_text="allowed files : ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/direction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='resultvideos',
            name='video',
            field=models.FileField(blank=True, help_text="allowed videos: ['mp4', 'mpeg', 'mpeg-4', 'm4v']", upload_to='videos/directionresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpeg', 'mpeg-4', 'm4v']), apps.common.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='directionsemployeeresult',
            name='files',
            field=models.ManyToManyField(blank=True, to='orders.resultfiles'),
        ),
    ]
