# Generated by Django 4.1.13 on 2023-12-20 05:32

import apps.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_resultfiles_remove_directionsemployeeresult_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directions',
            old_name='to_imams',
            new_name='required_to_employee',
        ),
        migrations.AddField(
            model_name='directions',
            name='required_to_district',
            field=models.ManyToManyField(blank=True, to='common.districts'),
        ),
        migrations.AddField(
            model_name='directions',
            name='required_to_region',
            field=models.ManyToManyField(to='common.regions'),
        ),
        migrations.AddField(
            model_name='directions',
            name='to_employee',
            field=models.ManyToManyField(blank=True, related_name='direction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_employee_result', to='orders.directions'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_employee_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='voice',
            field=models.FileField(blank=True, help_text="allowed images: ['mp3',]", upload_to='voices/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AlterField(
            model_name='resultfiles',
            name='file',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='resultimages',
            name='image',
            field=models.ImageField(blank=True, help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='resultvideos',
            name='video',
            field=models.FileField(blank=True, help_text="allowed videos: ['mp4', 'mpeg', 'mpeg-4', 'm4v']", upload_to='videos/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpeg', 'mpeg-4', 'm4v']), apps.common.validators.validate_file_size]),
        ),
    ]
