# Generated by Django 4.1.13 on 2023-12-22 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_rename_to_imams_directions_required_to_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directions',
            options={'ordering': ['-created_at'], 'verbose_name': "Ko'rsatma ", 'verbose_name_plural': "Ko'rsatmalar "},
        ),
        migrations.AlterModelOptions(
            name='directionsemployeeread',
            options={'ordering': ['-created_at'], 'verbose_name': "Ko'rsatma oqilishi ", 'verbose_name_plural': "Ko'rsatma oqilishlari "},
        ),
        migrations.AlterModelOptions(
            name='directionsemployeeresult',
            options={'ordering': ['-created_at'], 'verbose_name': "Ko'rsatma natija ", 'verbose_name_plural': "Ko'rsatma natijalari "},
        ),
        migrations.AlterModelOptions(
            name='resultfiles',
            options={'verbose_name': 'Fayl ', 'verbose_name_plural': 'Fayllar '},
        ),
        migrations.AlterModelOptions(
            name='resultimages',
            options={'verbose_name': 'Rasm ', 'verbose_name_plural': 'Rasmlar '},
        ),
        migrations.AlterModelOptions(
            name='resultvideos',
            options={'verbose_name': 'Video ', 'verbose_name_plural': 'Videolar '},
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_employee_result', to='orders.directions'),
        ),
        migrations.AlterUniqueTogether(
            name='directionsemployeeread',
            unique_together={('direction', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='directionsemployeeresult',
            unique_together={('direction', 'employee')},
        ),
    ]
