# Generated by Django 4.1.13 on 2023-12-23 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_alter_directions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directions',
            name='from_role',
            field=models.CharField(choices=[('1', 'Super Admin'), ('2', 'Region Admin'), ('3', 'District Admin')], default='1', max_length=18),
        ),
    ]
