# Generated by Django 4.1.13 on 2023-12-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('orders', '0013_directions_creator_alter_directions_from_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='required_to_region',
            field=models.ManyToManyField(blank=True, to='common.regions'),
        ),
    ]
