# Generated by Django 4.1.13 on 2023-12-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_directions_required_to_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
