# Generated by Django 4.1.13 on 2024-01-08 06:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_directions_required_to_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='to_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('REGION_ADMIN', '2'), ('DISTRICT_ADMIN', '3'), ('IMAM', '4'), ('SUB_IMAM', '5')], default=('REGION_ADMIN', '2'), max_length=18), default=list, size=4),
        ),
    ]
