# Generated by Django 4.1.13 on 2024-01-08 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_directions_to_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='to_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('2', 'Region Admin'), ('3', 'District Admin'), ('4', 'Imam'), ('5', 'Sub Imam')], default='4', max_length=18), default=list, size=4),
        ),
    ]
