# Generated by Django 4.1.13 on 2024-01-08 11:15

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_directions_to_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('file', models.FileField(help_text="allowed files : ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/direction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size])),
            ],
            options={
                'verbose_name': 'Fayl ',
                'verbose_name_plural': 'Fayllar ',
            },
        ),
        migrations.RemoveField(
            model_name='directions',
            name='file',
        ),
        migrations.AddField(
            model_name='directions',
            name='file',
            field=models.ManyToManyField(blank=True, to='orders.directionfiles'),
        ),
    ]
