# Generated by Django 4.1.13 on 2024-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('orders', '0024_directionfiles_remove_directions_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='to_region',
            field=models.ManyToManyField(blank=True, related_name='direction', to='common.regions'),
        ),
    ]
