# Generated by Django 4.1.13 on 2024-01-22 10:29

import apps.common.validators
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0010_alter_firedefenseimages_options'),
        ('common', '0002_alter_districts_name_alter_districts_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0026_alter_directionsemployeeread_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionfiles',
            name='file',
            field=models.FileField(help_text="allowed files : ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/direction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='comment',
            field=models.BooleanField(default=False, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='direction_type',
            field=models.CharField(choices=[('decision', 'Decision'), ('order', 'Order'), ('program', 'Program'), ('message', 'Message'), ('mission', 'Mission')], default='order', max_length=11, verbose_name='direction_type'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='file',
            field=models.ManyToManyField(blank=True, to='orders.directionfiles', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='file_bool',
            field=models.BooleanField(default=False, verbose_name='file_bool'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='from_date',
            field=models.DateField(verbose_name='from_date'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='from_role',
            field=models.CharField(choices=[('1', 'Super Admin'), ('2', 'Region Admin'), ('3', 'District Admin')], default='1', max_length=18, verbose_name='from_role'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='image',
            field=models.BooleanField(default=False, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='required_to_district',
            field=models.ManyToManyField(blank=True, to='common.districts', verbose_name='required_to_district'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='required_to_employee',
            field=models.ManyToManyField(blank=True, to='mosque.mosque', verbose_name='required_to_employee'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='required_to_region',
            field=models.ManyToManyField(blank=True, to='common.regions', verbose_name='required_to_region'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='to_date'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_district',
            field=models.ManyToManyField(blank=True, related_name='direction', to='common.districts', verbose_name='to_district'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_employee',
            field=models.ManyToManyField(blank=True, related_name='direction', to='mosque.mosque', verbose_name='to_employee'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_region',
            field=models.ManyToManyField(blank=True, related_name='direction', to='common.regions', verbose_name='to_region'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('2', 'Region Admin'), ('3', 'District Admin'), ('4', 'Imam'), ('5', 'Sub Imam')], default='4', max_length=18, null=True, verbose_name='to_role'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directions',
            name='types',
            field=models.CharField(choices=[('information', 'Information'), ('implement', 'Implement')], default='information', max_length=12, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='video',
            field=models.BooleanField(default=False, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='voice',
            field=models.BooleanField(default=False, verbose_name='voice'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeread',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionemployeeread', to='orders.directions', verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeread',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directionemployeeread', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeread',
            name='requirement',
            field=models.BooleanField(default=False, verbose_name='requirement'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeread',
            name='state',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('accepted', 'Accepted'), ('done', 'Done'), ('expired', 'Expired')], default='unseen', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_employee_result', to='orders.directions', verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_employee_result', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='files',
            field=models.ManyToManyField(blank=True, to='orders.resultfiles', verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='images',
            field=models.ManyToManyField(blank=True, to='orders.resultimages', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='videos',
            field=models.ManyToManyField(blank=True, to='orders.resultvideos', verbose_name='videos'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='voice',
            field=models.FileField(blank=True, help_text="allowed voices: ['mp3',]", upload_to='voices/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3']), apps.common.validators.validate_file_size], verbose_name='voice'),
        ),
        migrations.AlterField(
            model_name='resultfiles',
            name='file',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='resultimages',
            name='image',
            field=models.ImageField(blank=True, help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resultvideos',
            name='video',
            field=models.FileField(blank=True, help_text="allowed videos: ['mp4', 'mpeg', 'mpeg-4', 'm4v']", upload_to='videos/direction_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpeg', 'mpeg-4', 'm4v']), apps.common.validators.validate_video_size], verbose_name='video'),
        ),
    ]
