# Generated by Django 4.1.13 on 2024-01-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_directionfiles_file_alter_directions_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionsemployeeread',
            options={'ordering': ['-created_at'], 'verbose_name': "Ko'rsatma bildirishnoma ", 'verbose_name_plural': "Ko'rsatma bildirishnomalari "},
        ),
    ]
