# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_directionsemployeeread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionfiles',
            options={'verbose_name': "Ko'rsatma fayli ", 'verbose_name_plural': "Ko'rsatma fayllari "},
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_employee_result', to='orders.directions', verbose_name='direction'),
        ),
    ]
