# Generated by Django 4.1 on 2024-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_directionfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionsemployeeread',
            name='state',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('accepted', 'Accepted'), ('done', 'Done'), ('delayed', 'Delayed')], default='unseen', max_length=10, verbose_name='state'),
        ),
    ]
