# Generated by Django 4.1 on 2024-02-01 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_directionsemployeeresult_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directions',
            name='direction_type',
            field=models.CharField(choices=[('decision', 'decision'), ('order', 'order'), ('program', 'program'), ('message', 'message'), ('mission', 'mission')], default='order', max_length=11, verbose_name='direction_type'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='from_role',
            field=models.CharField(choices=[('1', 'super_admin'), ('2', 'region_admin'), ('3', 'district_admin')], default='1', max_length=18, verbose_name='from_role'),
        ),
        migrations.AlterField(
            model_name='directions',
            name='to_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('2', 'region_admin'), ('3', 'district_admin'), ('4', 'imam'), ('5', 'sub_imam')], default='4', max_length=18, null=True, verbose_name='to_role'), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directions',
            name='types',
            field=models.CharField(choices=[('information', 'information'), ('implement', 'implement')], default='information', max_length=12, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='directionsemployeeresult',
            name='state',
            field=models.CharField(choices=[('unseen', 'unseen'), ('accepted', 'accepted'), ('done', 'done'), ('delayed', 'delayed')], default='unseen', max_length=10, verbose_name='state'),
        ),
    ]
