# Generated by Django 4.1.13 on 2023-12-14 07:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('date', models.DateField()),
                ('marriage_image', models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='files/marriage_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('marriage_document', models.FileField(help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/marriage_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt'])])),
                ('fhdyo_document', models.FileField(help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/fhdyo_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt'])])),
                ('fhdyo_image', models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='files/fhdyo_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('mahr', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nikoh ',
                'verbose_name_plural': 'Nikohlar ',
            },
        ),
    ]
