# Generated by Django 4.1.13 on 2024-01-15 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0002_alter_marriage_fhdyo_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='fhdyo_image',
            field=models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/fhdyo_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='marriage_image',
            field=models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='image/marriage_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
