# Generated by Django 4.1.13 on 2024-01-22 09:10

import apps.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marriage', '0003_alter_marriage_fhdyo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nikoh ', 'verbose_name_plural': 'Nikohlar '},
        ),
        migrations.AlterField(
            model_name='marriage',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='fhdyo_document',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/fhdyo_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='fhdyo_document'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='fhdyo_image',
            field=models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/fhdyo_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='fhdyo_image'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriage', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='mahr',
            field=models.FloatField(default=0, verbose_name='mahr'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='marriage_document',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/marriage_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='marriage_document'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='marriage_image',
            field=models.FileField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='image/marriage_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='marriage_image'),
        ),
    ]
