# Generated by Django 4.1.13 on 2023-12-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='filter_type',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='text', max_length=255),
        ),
    ]
