# Generated by Django 4.1.13 on 2024-01-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ceremony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='imam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='types',
            field=models.CharField(choices=[('funeral', 'Funeral'), ('mourning', 'Mourning')], default='funeral', max_length=15, verbose_name='types'),
        ),
    ]
