# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0002_alter_ceremony_comment_alter_ceremony_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceremony',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marosim ', 'verbose_name_plural': 'Marosimlar '},
        ),
    ]
