# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0003_alter_ceremony_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='types',
            field=models.CharField(choices=[('funeral', 'funeral'), ('mourning', 'mourning')], default='funeral', max_length=15, verbose_name='types'),
        ),
    ]
