# Generated by Django 4.1.13 on 2023-12-15 13:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Invalid'), ('2', 'Poor'), ('3', 'None Breadwinner'), ('4', 'Student'), ('5', 'Other')], default='2', max_length=22)),
                ('help_type', models.CharField(choices=[('1', 'Money'), ('2', 'Food'), ('3', 'Closes'), ('4', 'Medicine'), ('5', 'Other')], max_length=22)),
                ('from_who', models.CharField(choices=[('1', 'Mosque'), ('2', 'Sponsor'), ('3', 'Zakat'), ('4', 'Fidya'), ('5', 'Fitr'), ('6', 'Other')], max_length=22)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_charity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hayriya ',
                'verbose_name_plural': 'Hayriyalar ',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/charity/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='charity.charity')),
            ],
            options={
                'verbose_name': 'Hayriya rasmi ',
                'verbose_name_plural': 'Hayriya rasmilari ',
            },
        ),
    ]
