# Generated by Django 4.1.13 on 2023-12-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='charity',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
