# Generated by Django 4.1.13 on 2023-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_rename_type_charity_types_charity_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='charity',
        ),
        migrations.AddField(
            model_name='charity',
            name='images',
            field=models.ManyToManyField(to='charity.images'),
        ),
    ]
