# Generated by Django 4.1.13 on 2023-12-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_images_charity_charity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='images',
            field=models.ManyToManyField(blank=True, to='charity.images'),
        ),
    ]
