# Generated by Django 4.1.13 on 2024-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='from_who',
            field=models.CharField(choices=[('mosque', 'Mosque'), ('sponsor', 'Sponsor'), ('zakat', 'Zakat'), ('fidya', 'Fidya'), ('fitr', 'Fitr'), ('other', 'Other')], max_length=22),
        ),
        migrations.AlterField(
            model_name='charity',
            name='help_type',
            field=models.CharField(choices=[('money', 'Money'), ('food', 'Food'), ('closes', 'Closes'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=22),
        ),
        migrations.AlterField(
            model_name='charity',
            name='types',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('poor', 'Poor'), ('none_breadwinner', 'None Breadwinner'), ('student', 'Student'), ('other', 'Other')], default='poor', max_length=22),
        ),
    ]
