# Generated by Django 4.1.13 on 2024-01-20 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0005_alter_charity_from_who_alter_charity_help_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='from_who',
            field=models.CharField(choices=[('mosque', 'Mosque'), ('sponsor', 'Sponsor'), ('zakat', 'Zakat'), ('fidya', 'Fidya'), ('fitr', 'Fitr'), ('other', 'Other')], max_length=22, verbose_name='from_who'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='help_type',
            field=models.CharField(choices=[('money', 'Money'), ('food', 'Food'), ('closes', 'Closes'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=22, verbose_name='help_type'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='images',
            field=models.ManyToManyField(blank=True, to='charity.images', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_charity', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='summa',
            field=models.FloatField(default=0, verbose_name='summa'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='types',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('poor', 'Poor'), ('none_breadwinner', 'None Breadwinner'), ('student', 'Student'), ('other', 'Other')], default='poor', max_length=22, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/charity/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='image'),
        ),
    ]
