# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayriya ', 'verbose_name_plural': 'Hayriyalar '},
        ),
        migrations.AlterField(
            model_name='charity',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
