# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_alter_charity_options_alter_charity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='from_who',
            field=models.CharField(choices=[('mosque', 'mosque'), ('sponsor', 'sponsor'), ('zakat', 'zakat'), ('fidya', 'fidya'), ('fitr', 'fitr'), ('other', 'other')], max_length=22, verbose_name='from_who'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='help_type',
            field=models.CharField(choices=[('money', 'money'), ('food', 'food'), ('closes', 'closes'), ('medicine', 'medicine'), ('other', 'other')], max_length=22, verbose_name='help_type'),
        ),
        migrations.AlterField(
            model_name='charity',
            name='types',
            field=models.CharField(choices=[('invalid', 'invalid'), ('poor', 'poor'), ('none_breadwinner', 'none_breadwinner'), ('student', 'student'), ('other', 'other')], default='poor', max_length=22, verbose_name='types'),
        ),
    ]
