# Generated by Django 4.1.13 on 2023-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='charity_promotion',
        ),
        migrations.AddField(
            model_name='charitypromotion',
            name='images',
            field=models.ManyToManyField(blank=True, to='charity_promotion.images'),
        ),
    ]
