# Generated by Django 4.1.13 on 2023-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_promotion', '0002_remove_images_charity_promotion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='CharityPromotionImages',
        ),
    ]
