# Generated by Django 4.1.13 on 2024-01-20 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity_promotion', '0003_rename_images_charitypromotionimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypromotion',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='from_who',
            field=models.CharField(choices=[('mosque', 'Mosque'), ('sponsor', 'Sponsor'), ('zakat', 'Zakat'), ('fidya', 'Fidya'), ('fitr', 'Fitr'), ('other', 'Other')], max_length=22, verbose_name='from_who'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='help_type',
            field=models.CharField(choices=[('money', 'Money'), ('food', 'Food'), ('closes', 'Closes'), ('medicine', 'Medicine'), ('other', 'Other')], max_length=22, verbose_name='help_type'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='images',
            field=models.ManyToManyField(blank=True, to='charity_promotion.charitypromotionimages', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_charity_promotion', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='participant',
            field=models.CharField(choices=[('initiative', 'Initiative'), ('participant', 'Participant'), ('other', 'Other')], default='initiative', max_length=22, verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='types',
            field=models.CharField(choices=[('building', 'Building'), ('water_discharge', 'Water Discharge'), ('other', 'Other')], default='building', max_length=22, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='charitypromotionimages',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/charity_promotion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='image'),
        ),
    ]
