# Generated by Django 4.1.13 on 2024-01-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_promotion', '0005_alter_charitypromotionimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypromotion',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
