# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_promotion', '0006_alter_charitypromotion_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charitypromotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hayriya aksiyasi ', 'verbose_name_plural': 'Hayriya aksiyalari '},
        ),
    ]
