# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_promotion', '0007_alter_charitypromotion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypromotion',
            name='from_who',
            field=models.CharField(choices=[('mosque', 'mosque'), ('sponsor', 'sponsor'), ('zakat', 'zakat'), ('fidya', 'fidya'), ('fitr', 'fitr'), ('other', 'other')], max_length=22, verbose_name='from_who'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='help_type',
            field=models.CharField(choices=[('money', 'money'), ('food', 'food'), ('closes', 'closes'), ('medicine', 'medicine'), ('other', 'other')], max_length=22, verbose_name='help_type'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='participant',
            field=models.CharField(choices=[('initiative', 'initiative'), ('participant', 'participant'), ('other', 'other')], default='initiative', max_length=22, verbose_name='participant'),
        ),
        migrations.AlterField(
            model_name='charitypromotion',
            name='types',
            field=models.CharField(choices=[('building', 'building'), ('water_discharge', 'water_discharge'), ('other', 'other')], default='building', max_length=22, verbose_name='types'),
        ),
    ]
