# Generated by Django 4.1.13 on 2023-12-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('comment', models.TextField(blank=True)),
                ('participants', models.CharField(blank=True, choices=[('1', 'Teens'), ('2', 'Womans'), ('3', 'Mans'), ('4', 'Older Man'), ('5', 'Mix')], max_length=20)),
                ('types', models.CharField(blank=True, choices=[('1', 'Social Environment'), ('2', 'Prevent Crime'), ('3', 'Prevent Suicide'), ('4', 'Educational'), ('5', 'Other')], max_length=20)),
                ('date', models.DateField(blank=True)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_imam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahalla ',
                'verbose_name_plural': 'Mahallalar ',
            },
        ),
    ]
