# Generated by Django 4.1.13 on 2023-12-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='participants',
            field=models.CharField(choices=[('1', 'Teens'), ('2', 'Womans'), ('3', 'Mans'), ('4', 'Older Man'), ('5', 'Mix')], max_length=20),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='types',
            field=models.CharField(choices=[('1', 'Social Environment'), ('2', 'Prevent Crime'), ('3', 'Prevent Suicide'), ('4', 'Educational'), ('5', 'Other')], max_length=20),
        ),
    ]
