# Generated by Django 4.1.13 on 2024-01-22 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborhood', '0002_alter_neighborhood_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_imam', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='participants',
            field=models.CharField(choices=[('teens', 'Teens'), ('womans', 'Womans'), ('mans', 'Mans'), ('older_man', 'Older Man'), ('mix', 'Mix')], max_length=20, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='types',
            field=models.CharField(choices=[('social_environment', 'Social Environment'), ('prevent_crime', 'Prevent Crime'), ('prevent_suicide', 'Prevent Suicide'), ('educational', 'Educational'), ('other', 'Other')], max_length=20, verbose_name='types'),
        ),
    ]
