# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_alter_neighborhood_comment_alter_neighborhood_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahalla ', 'verbose_name_plural': 'Mahallalar '},
        ),
    ]
