# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0004_alter_neighborhood_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='participants',
            field=models.CharField(choices=[('teens', 'teens'), ('womans', 'womans'), ('mans', 'mans'), ('older_man', 'older_man'), ('mix', 'mix')], max_length=20, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='types',
            field=models.CharField(choices=[('social_environment', 'social_environment'), ('prevent_crime', 'prevent_crime'), ('prevent_suicide', 'prevent_suicide'), ('educational', 'educational'), ('other', 'other')], max_length=20, verbose_name='types'),
        ),
    ]
