# Generated by Django 4.1.13 on 2023-12-14 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'verbose_name': "To'y ", 'verbose_name_plural': "To'ylar "},
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='fhdyo_file',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='mahir',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='wedding_document',
        ),
        migrations.AddField(
            model_name='wedding',
            name='title',
            field=models.CharField(default='title', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='types',
            field=models.CharField(choices=[('1', 'Marriage'), ('2', 'Aqeeqah Sunant'), ('3', 'Hamd')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='imam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
