# Generated by Django 4.1.13 on 2024-01-22 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wedding', '0002_alter_wedding_options_remove_wedding_fhdyo_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='imam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='types',
            field=models.CharField(choices=[('marriage', 'Marriage'), ('aqeeqah_sunant', 'Aqeeqah Sunant'), ('hamd', 'Hamd')], default='marriage', max_length=15, verbose_name='types'),
        ),
    ]
