# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_wedding_comment_alter_wedding_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wedding',
            options={'ordering': ['-created_at'], 'verbose_name': "To'y ", 'verbose_name_plural': "To'ylar "},
        ),
    ]
