# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_alter_wedding_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='types',
            field=models.CharField(choices=[('marriage', 'marriage'), ('aqeeqah_sunant', 'aqeeqah_sunant'), ('hamd', 'hamd')], default='marriage', max_length=15, verbose_name='types'),
        ),
    ]
