# Generated by Django 4.1.13 on 2023-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('REGION_ADMIN', 'Region Admin'), ('DISTRICT_ADMIN', 'District Admin'), ('IMAM', 'Imam'), ('SUB_IMAM', 'Sub Imam')], default='IMAM', max_length=18, null=True),
        ),
    ]
