# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'super_admin'), ('2', 'region_admin'), ('3', 'district_admin'), ('4', 'imam'), ('5', 'sub_imam')], default='4', max_length=18, null=True, verbose_name='role'),
        ),
    ]
