# Generated by Django 4.1.13 on 2023-12-15 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Holiday'), ('2', 'Hashar'), ('3', 'Opening Ceremony'), ('4', 'Other')], default='1', max_length=22)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_community_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jamoat tadbiri ',
                'verbose_name_plural': 'Jamoat tadbirlari ',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/community_event/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community_events.communityevents')),
            ],
            options={
                'verbose_name': 'Jamoat tadbiri rasmi ',
                'verbose_name_plural': 'Jamoat tadbirlari rasmi ',
            },
        ),
    ]
