# Generated by Django 4.1.13 on 2023-12-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='event',
        ),
        migrations.AddField(
            model_name='communityevents',
            name='images',
            field=models.ManyToManyField(blank=True, to='community_events.images'),
        ),
    ]
