# Generated by Django 4.1.13 on 2024-01-20 09:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community_events', '0002_remove_images_event_communityevents_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityevents',
            name='type',
        ),
        migrations.AddField(
            model_name='communityevents',
            name='types',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('hashar', 'Hashar'), ('opening_ceremony', 'Opening Ceremony'), ('other', 'Other')], default='holiday', max_length=22, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='communityevents',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='communityevents',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='communityevents',
            name='images',
            field=models.ManyToManyField(blank=True, to='community_events.images', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='communityevents',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_community_events', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/community_event/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='image'),
        ),
    ]
