# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0004_alter_images_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communityevents',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jamoat tadbiri ', 'verbose_name_plural': 'Jamoat tadbirlari '},
        ),
        migrations.AlterField(
            model_name='communityevents',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
