# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_events', '0005_alter_communityevents_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevents',
            name='types',
            field=models.CharField(choices=[('holiday', 'holiday'), ('hashar', 'hashar'), ('opening_ceremony', 'opening_ceremony'), ('other', 'other')], default='holiday', max_length=22, verbose_name='types'),
        ),
    ]
