# Generated by Django 4.1.13 on 2023-12-15 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('comment', models.TextField(blank=True)),
                ('causes', models.CharField(choices=[('1', 'Property'), ('2', 'Heritage'), ('3', 'Jealousy'), ('4', 'Not Understanding'), ('5', 'Other')], max_length=20)),
                ('types', models.CharField(choices=[('1', 'Brothers'), ('2', 'Couple'), ('3', 'Parent And Child')], max_length=20)),
                ('results', models.CharField(choices=[('1', 'Positive'), ('2', 'Negative'), ('3', 'Abstract')], max_length=20)),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_conflicts_imam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oilaviy muammo ',
                'verbose_name_plural': 'Oilaviy muammolar ',
            },
        ),
    ]
