# Generated by Django 4.1.13 on 2024-01-22 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family_conflicts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyconflict',
            name='causes',
            field=models.CharField(choices=[('property', 'Property'), ('heritage', 'Heritage'), ('jealousy', 'Jealousy'), ('not_understanding', 'Not Understanding'), ('other', 'Other')], max_length=20, verbose_name='causes'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_conflicts_imam', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='results',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('abstract', 'Abstract')], max_length=20, verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='types',
            field=models.CharField(choices=[('brothers', 'Brothers'), ('couple', 'Couple'), ('parent_and_child', 'Parent And Child')], max_length=20, verbose_name='types'),
        ),
    ]
