# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_conflicts', '0002_alter_familyconflict_causes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyconflict',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oilaviy muammo ', 'verbose_name_plural': 'Oilaviy muammolar '},
        ),
    ]
