# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_conflicts', '0003_alter_familyconflict_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyconflict',
            name='causes',
            field=models.CharField(choices=[('property', 'property'), ('heritage', 'heritage'), ('jealousy', 'jealousy'), ('not_understanding', 'not_understanding'), ('other', 'other')], max_length=20, verbose_name='causes'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='results',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('abstract', 'abstract')], max_length=20, verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='familyconflict',
            name='types',
            field=models.CharField(choices=[('brothers', 'brothers'), ('couple', 'couple'), ('parent_and_child', 'parent_and_child')], max_length=20, verbose_name='types'),
        ),
    ]
