# Generated by Django 4.1.13 on 2023-12-15 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReligiousAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Fiqh'), ('2', 'Creed'), ('3', 'Other')], default='3', max_length=12)),
                ('choices', models.CharField(choices=[('1', 'Prayers'), ('2', 'Spleen'), ('3', 'Commerce'), ('4', 'Debt'), ('5', 'Heritage'), ('6', 'Faith'), ('7', 'Jihad'), ('8', 'Takfir'), ('9', 'Vasiyla'), ('10', 'Other')], max_length=12)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_religious_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diniy maslahat ',
                'verbose_name_plural': 'Diniy maslahatlar ',
            },
        ),
    ]
