# Generated by Django 4.1.13 on 2024-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious_advice', '0002_alter_religiousadvice_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religiousadvice',
            name='choices',
            field=models.CharField(choices=[('prayers', 'Prayers'), ('spleen', 'Spleen'), ('commerce', 'Commerce'), ('debt', 'Debt'), ('heritage', 'Heritage'), ('faith', 'Faith'), ('jihad', 'Jihad'), ('takfir', 'Takfir'), ('vasiyla', 'Vasiyla'), ('other', 'Other')], max_length=12, verbose_name='choices'),
        ),
    ]
