# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious_advice', '0003_alter_religiousadvice_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='religiousadvice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Diniy maslahat ', 'verbose_name_plural': 'Diniy maslahatlar '},
        ),
        migrations.AlterField(
            model_name='religiousadvice',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
