# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious_advice', '0004_alter_religiousadvice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religiousadvice',
            name='choices',
            field=models.CharField(choices=[('prayers', 'prayers'), ('spleen', 'spleen'), ('commerce', 'commerce'), ('debt', 'debt'), ('heritage', 'heritage'), ('faith', 'faith'), ('jihad', 'jihad'), ('takfir', 'takfir'), ('vasiyla', 'vasiyla'), ('other', 'other')], max_length=12, verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='religiousadvice',
            name='type',
            field=models.CharField(choices=[('fiqh', 'fiqh'), ('creed', 'creed'), ('other', 'other')], default='other', max_length=12, verbose_name='type'),
        ),
    ]
