# Generated by Django 4.1.13 on 2023-12-15 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Electron'), ('2', 'Print')], default='2', max_length=22)),
                ('comment', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('publication', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_type', models.CharField(blank=True, choices=[('1', 'Newspaper'), ('2', 'Journal')], max_length=10, null=True)),
                ('article_types', models.CharField(blank=True, choices=[('1', 'Islam Nuri'), ('2', 'Hidayat'), ('3', 'Imam Bukxariy'), ('4', 'Mumins'), ('5', 'Other')], max_length=15, null=True)),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqola ',
                'verbose_name_plural': 'Maqolalar ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('1', 'Religious'), ('2', 'Educational')], default='1', max_length=22)),
                ('publication', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitob ',
                'verbose_name_plural': 'Kitoblar ',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/article', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scientific_activity.article')),
            ],
            options={
                'verbose_name': 'Maqola rasmi ',
                'verbose_name_plural': 'Maqola rasmlari ',
            },
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/book', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scientific_activity.book')),
            ],
            options={
                'verbose_name': 'Kitob rasmi ',
                'verbose_name_plural': 'Kitob rasmlari ',
            },
        ),
    ]
