# Generated by Django 4.1.13 on 2023-12-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimages',
            name='book',
        ),
        migrations.RemoveField(
            model_name='images',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='scientific_activity.images'),
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(blank=True, to='scientific_activity.bookimages'),
        ),
    ]
