# Generated by Django 4.1.13 on 2024-01-22 14:30

import apps.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scientific_activity', '0002_remove_bookimages_book_remove_images_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_types',
            field=models.CharField(blank=True, choices=[('islam_nuri', 'Islam Nuri'), ('hidayat', 'Hidayat'), ('imam_bukxariy', 'Imam Bukxariy'), ('mumins', 'Mumins'), ('other', 'Other')], max_length=15, null=True, verbose_name='article_types'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(blank=True, to='scientific_activity.images', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_articles', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('newspaper', 'Newspaper'), ('journal', 'Journal')], max_length=10, null=True, verbose_name='publication_type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('electron', 'Electron'), ('print', 'Print')], default='print', max_length=22, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='direction',
            field=models.CharField(choices=[('religious', 'Religious'), ('educational', 'Educational')], default='religious', max_length=22, verbose_name='direction'),
        ),
        migrations.AlterField(
            model_name='book',
            name='images',
            field=models.ManyToManyField(blank=True, to='scientific_activity.bookimages', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_books', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='publication'),
        ),
        migrations.AlterField(
            model_name='bookimages',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/book', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/article', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
    ]
