# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_activity', '0004_alter_article_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_types',
            field=models.CharField(blank=True, choices=[('islam_nuri', 'islam_nuri'), ('hidayat', 'hidayat'), ('imam_bukxariy', 'imam_bukxariy'), ('mumins', 'mumins'), ('other', 'other')], max_length=15, null=True, verbose_name='article_types'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('newspaper', 'newspaper'), ('journal', 'journal')], max_length=10, null=True, verbose_name='publication_type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('electron', 'electron'), ('print', 'print')], default='print', max_length=22, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='book',
            name='direction',
            field=models.CharField(choices=[('religious', 'religious'), ('educational', 'educational')], default='religious', max_length=22, verbose_name='direction'),
        ),
    ]
