# Generated by Django 4.1.13 on 2023-12-13 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('date', models.DateField()),
                ('death_document', models.FileField(help_text="allowed files: ['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx']", upload_to='files/death_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])])),
                ('file', models.FileField(help_text="allowed files: ['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx']", upload_to='files/death_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])])),
                ('comment', models.TextField(blank=True, null=True)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'lim ",
                'verbose_name_plural': "O'limlar ",
            },
        ),
    ]
