# Generated by Django 4.1.13 on 2023-12-14 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='death_document',
        ),
        migrations.AddField(
            model_name='death',
            name='image',
            field=models.ImageField(blank=True, help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='files/death_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='death',
            name='file',
            field=models.FileField(help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/death_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt'])]),
        ),
    ]
