# Generated by Django 4.1.13 on 2024-01-20 09:09

import apps.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('death', '0003_alter_death_file_alter_death_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='death',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='death',
            name='file',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/death_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='death',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='files/death_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='death',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
    ]
