# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death', '0005_alter_death_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='death',
            options={'ordering': ['-created_at'], 'verbose_name': "O'lim ", 'verbose_name_plural': "O'limlar "},
        ),
    ]
