# Generated by Django 4.1.13 on 2023-12-15 07:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Need Social Assistance'), ('2', 'Prone To Crime'), ('3', 'Other')], default='3', max_length=22)),
                ('title', models.CharField(max_length=300)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_individual_conversation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saxsiy suhbat ',
                'verbose_name_plural': 'Saxsiy suhbatlar ',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/conversation_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='individual_conversations.individualconversation')),
            ],
            options={
                'verbose_name': 'Suhbat rasmi ',
                'verbose_name_plural': 'Suhbat rasmlari ',
            },
        ),
    ]
