# Generated by Django 4.1.13 on 2023-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualconversation',
            name='type',
            field=models.CharField(choices=[('1', 'Need Social Assistance'), ('2', 'Prone To Crime'), ('3', 'Other')], default='1', max_length=22),
        ),
    ]
