# Generated by Django 4.1.13 on 2023-12-25 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0003_alter_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualConversationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/conversation_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
            options={
                'verbose_name': 'Suhbat rasmi ',
                'verbose_name_plural': 'Suhbat rasmlari ',
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='individualconversation',
            name='images',
            field=models.ManyToManyField(to='individual_conversations.individualconversationimages'),
        ),
    ]
