# Generated by Django 4.1.13 on 2024-01-22 09:10

import apps.common.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('individual_conversations', '0004_individualconversationimages_delete_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualconversation',
            name='type',
        ),
        migrations.AddField(
            model_name='individualconversation',
            name='types',
            field=models.CharField(choices=[('need_social_assistance', 'Need Social Assistance'), ('prone_to_crime', 'Prone To Crime'), ('other', 'Other')], default='need_social_assistance', max_length=22, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='individualconversation',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='individualconversation',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='individualconversation',
            name='images',
            field=models.ManyToManyField(to='individual_conversations.individualconversationimages', verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='individualconversation',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_individual_conversation', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='individualconversation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='individualconversationimages',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/conversation_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
    ]
