# Generated by Django 4.1.13 on 2024-01-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0005_remove_individualconversation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualconversation',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
