# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0006_alter_individualconversation_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualconversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saxsiy suhbat ', 'verbose_name_plural': 'Saxsiy suhbatlar '},
        ),
    ]
