# Generated by Django 4.1.13 on 2024-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0007_alter_individualconversation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualconversation',
            name='types',
            field=models.CharField(choices=[('need_social_assistance', 'Need Social Assistance'), ('prone_to_crime', 'Prone To Crime'), ('other', 'Other')], max_length=22, verbose_name='types'),
        ),
    ]
