# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_conversations', '0008_alter_individualconversation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualconversation',
            name='types',
            field=models.CharField(choices=[('need_social_assistance', 'need_social_assistance'), ('prone_to_crime', 'prone_to_crime'), ('other', 'other')], max_length=22, verbose_name='types'),
        ),
    ]
