# Generated by Django 4.1.13 on 2023-12-06 15:30

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', location_field.models.plain.PlainLocationField(max_length=63)),
                ('image', models.ImageField(default='default/default_user.png', upload_to='images/profil_images/')),
                ('bith_date', models.DateField()),
                ('education', models.CharField(choices=[("O'RTA MAXSUS", 'Medium Special'), ('OLIY', 'High'), ('MALUMOTSIZ', 'None')], default="O'RTA MAXSUS", max_length=50, null=True)),
                ('graduated_univer', models.CharField(choices=[('Toshkent islom instituti', 'Tashkent Islamic Institute'), ('Hadis ilmi maktabi', 'School Of Hadith Science'), ('Mir Arab Oliy Madrasasi', 'Mir Arab Higher Madrasah'), ("Ko'kaldosh", 'Kokaldosh'), ('Mir Arab', 'Mir Arab'), ('Xoja Buxoriy', 'Khoja Bukhari'), ('Imom Termiziy', 'Imam Termizi'), ('Faxriddin ar-Roziy', 'Fakhriddin Ar Razi'), ('Muhammad al-Beruniy', 'Muhammad Al Beruni'), ('Sayyid Muhiddin Maxdum', 'Sayyid Muhiddin Makhdum'), ('Hidoya', 'Hidayah'), ('Xadichai Kubro', 'Khadichai Kubro'), ("Jo'ybori kalon", 'Joybori Kalon'), ('Boshqa', 'Another')], default='Toshkent islom instituti', max_length=70, null=True)),
                ('graduated_year', models.DateField()),
                ('diploma_number', models.IntegerField()),
                ('academic_degree', models.CharField(choices=[('Bakalavr', 'Bachelor'), ('Magistr', 'Master'), ('Doktorant', 'Phd'), ('Doktor', 'Dsc')], default='Bakalavr', max_length=50, null=True)),
                ('achievement', models.CharField(choices=[('Davlat mukofotlari', 'State Awards'), ('Esdalik nishonlari', 'Commemorative Badges'), ('Belgilar', 'Signs'), ('Minnatdorchilik', 'Gratitude'), ('Maqtov', 'Compliment'), ('Faxriy unvonlar', 'Honorary Titles'), ("imtihon tanlovi g'olibining diplomlari", 'Diplomas Of The Winner Of The Exam Competition'), ('tanlov g‘oliblarining diplomlari', 'Diplomas Of Competition Winners'), ('xalqaro mukofotlar', 'International Awards')], default='Davlat mukofotlari', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Hodim ',
                'verbose_name_plural': 'Hodimlar ',
            },
        ),
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('as_who', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workactivity', to='employee.employee')),
            ],
            options={
                'verbose_name': 'ish faoliyati ',
                'verbose_name_plural': 'ish faoliyati ',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(max_length=60)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='employee.employee')),
            ],
            options={
                'verbose_name': 'ijtimoiy tarmoq ',
                'verbose_name_plural': 'ijtimoiy tarmoq ',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('activity', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(default='default/no_photo.png', upload_to='images/employee_activity/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='employee.employee')),
            ],
            options={
                'verbose_name': 'tashabbusi ',
                'verbose_name_plural': 'tashabbuslari ',
            },
        ),
    ]
