# Generated by Django 4.1.13 on 2023-12-06 15:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('Bakalavr', 'Bachelor'), ('Magistr', 'Master'), ('Doktorant', 'Phd'), ('Doktor', 'Dsc')], default='Bakalavr', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='achievement',
            field=models.CharField(blank=True, choices=[('Davlat mukofotlari', 'State Awards'), ('Esdalik nishonlari', 'Commemorative Badges'), ('Belgilar', 'Signs'), ('Minnatdorchilik', 'Gratitude'), ('Maqtov', 'Compliment'), ('Faxriy unvonlar', 'Honorary Titles'), ("imtihon tanlovi g'olibining diplomlari", 'Diplomas Of The Winner Of The Exam Competition'), ('tanlov g‘oliblarining diplomlari', 'Diplomas Of Competition Winners'), ('xalqaro mukofotlar', 'International Awards')], default='Davlat mukofotlari', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='diploma_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[("O'RTA MAXSUS", 'Medium Special'), ('OLIY', 'High'), ('MALUMOTSIZ', 'None')], default="O'RTA MAXSUS", max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_univer',
            field=models.CharField(blank=True, choices=[('Toshkent islom instituti', 'Tashkent Islamic Institute'), ('Hadis ilmi maktabi', 'School Of Hadith Science'), ('Mir Arab Oliy Madrasasi', 'Mir Arab Higher Madrasah'), ("Ko'kaldosh", 'Kokaldosh'), ('Mir Arab', 'Mir Arab'), ('Xoja Buxoriy', 'Khoja Bukhari'), ('Imom Termiziy', 'Imam Termizi'), ('Faxriddin ar-Roziy', 'Fakhriddin Ar Razi'), ('Muhammad al-Beruniy', 'Muhammad Al Beruni'), ('Sayyid Muhiddin Maxdum', 'Sayyid Muhiddin Makhdum'), ('Hidoya', 'Hidayah'), ('Xadichai Kubro', 'Khadichai Kubro'), ("Jo'ybori kalon", 'Joybori Kalon'), ('Boshqa', 'Another')], default='Toshkent islom instituti', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Tik Tok', 'Tik Tok'), ('Twitter', 'Twitter'), ('YouTube', 'Youtube'), ('WhatsApp', 'Whatsapp')], default='Telegram', max_length=30),
        ),
    ]
