# Generated by Django 4.1.13 on 2023-12-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_academic_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bith_date',
            new_name='birth_date',
        ),
    ]
