# Generated by Django 4.1.13 on 2023-12-14 07:16

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_workactivity_employee_delete_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default/default_user.png', help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/profil_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
