# Generated by Django 4.1.13 on 2023-12-17 05:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_graduated_year_alter_employee_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Ijtimoiy tarmoq ', 'verbose_name_plural': 'Ijtimoiy tarmoq '},
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('1', 'Bachelor'), ('2', 'Master'), ('3', 'Phd'), ('4', 'Dsc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='achievement',
            field=models.CharField(blank=True, choices=[('1', 'State Awards'), ('2', 'Commemorative Badges'), ('3', 'Signs'), ('4', 'Gratitude'), ('5', 'Compliment'), ('6', 'Honorary Titles'), ('7', 'Diplomas Of The Winner Of The Exam Competition'), ('8', 'Diplomas Of Competition Winners'), ('9', 'International Awards')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Medium Special'), ('2', 'High'), ('3', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_univer',
            field=models.CharField(blank=True, choices=[('1', 'Tashkent Islamic Institute'), ('2', 'School Of Hadith Science'), ('3', 'Mir Arab Higher Madrasah'), ('4', 'Kokaldosh'), ('5', 'Mir Arab'), ('6', 'Khoja Bukhari'), ('7', 'Imam Termizi'), ('8', 'Fakhriddin Ar Razi'), ('9', 'Muhammad Al Beruni'), ('10', 'Sayyid Muhiddin Makhdum'), ('11', 'Hidayah'), ('12', 'Khadichai Kubro'), ('13', 'Joybori Kalon'), ('14', 'Another')], max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_year',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('1', 'Telegram'), ('2', 'Instagram'), ('3', 'Facebook'), ('4', 'Tik Tok'), ('5', 'Twitter'), ('6', 'Youtube'), ('7', 'Whatsapp')], max_length=30),
        ),
    ]
