# Generated by Django 4.1.13 on 2023-12-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_socialmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Hodim ', 'verbose_name_plural': 'Hodimlar '},
        ),
    ]
