# Generated by Django 4.1.13 on 2024-01-07 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0007_mosque_image'),
        ('employee', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_user.jpg', help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/profil_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mosque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='mosque.mosque'),
        ),
    ]
