# Generated by Django 4.1.13 on 2024-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_position_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='graduated_univer',
        ),
        migrations.AddField(
            model_name='employee',
            name='graduated_univer',
            field=models.ManyToManyField(blank=True, to='employee.graduation'),
        ),
    ]
