# Generated by Django 4.1.13 on 2024-01-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='graduated_univer',
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_year',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduated_univer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.graduation'),
        ),
    ]
