# Generated by Django 4.1.13 on 2024-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_employee_graduated_univer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('1', 'Medium Special'), ('2', 'High'), ('3', 'None')], default='3', max_length=50),
        ),
    ]
