# Generated by Django 4.1.13 on 2024-01-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('1', 'Bachelor'), ('2', 'Master'), ('3', 'Phd'), ('4', 'Dsc'), ('5', 'None')], default='5', max_length=50),
        ),
    ]
