# Generated by Django 4.1.13 on 2024-01-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id'], 'verbose_name': 'Xodim ', 'verbose_name_plural': 'Xodimlar '},
        ),
    ]
