# Generated by Django 4.1.13 on 2024-01-20 10:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0008_alter_mosque_mosque_heating_fuel_and_more'),
        ('employee', '0016_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Idora ', 'verbose_name_plural': 'Idoralar '},
        ),
        migrations.AlterModelOptions(
            name='graduation',
            options={'verbose_name': 'Universitet ', 'verbose_name_plural': 'Universitetlar '},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Lavozim ', 'verbose_name_plural': 'Lavozimlar '},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default='name', max_length=50, verbose_name='middle_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'Phd'), ('dsc', 'Dsc'), ('none', 'None')], default='none', max_length=50, verbose_name='academic_degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='achievement',
            field=models.CharField(blank=True, choices=[('state_awards', 'State Awards'), ('commemorative_badges', 'Commemorative Badges'), ('signs', 'Signs'), ('gratitude', 'Gratitude'), ('compliment', 'Compliment'), ('honorary_titles', 'Honorary Titles'), ('diplomas_of_the_winner_of_the_exam_competition', 'Diplomas Of The Winner Of The Exam Competition'), ('diplomas_of_competition_winners', 'Diplomas Of Competition Winners'), ('international_awards', 'International Awards')], max_length=50, verbose_name='achievement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='diploma_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='diploma_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('medium_special', 'Medium Special'), ('high', 'High'), ('none', 'None')], default='none', max_length=50, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_univer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.graduation', verbose_name='graduated_univer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='graduated_year',
            field=models.DateField(default='2000-01-01', verbose_name='graduated_year'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_user.jpg', help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/profil_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='mosque.mosque', verbose_name='mosque'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, choices=[('uzbek', 'Uzbek'), ('russian', 'Russian'), ('kazakh', 'Kazakh'), ('tajik', 'Tajik'), ('turkmen', 'Turkmen')], default='uzbek', max_length=10, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='employee.department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='employee.employee', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(max_length=60, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tik_tok', 'Tik Tok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('whatsapp', 'Whatsapp')], max_length=30, verbose_name='social_media'),
        ),
    ]
