# Generated by Django 4.1.13 on 2024-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_department_options_alter_graduation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('associate_professor', 'Associate Professor'), ('professor', 'Professor'), ('none', 'None')], default='none', max_length=50, verbose_name='academic_title'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='birth_place'),
        ),
        migrations.AddField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, choices=[('uzxdp', 'Uzxdp'), ('sdp', 'Sdp'), ('uzlidep', 'Uzlidep'), ('uzmtdp', 'Uzmtdp'), ('uzep', 'Uzep'), ('none', 'None')], default='none', max_length=50, verbose_name='party'),
        ),
        migrations.AddField(
            model_name='employee',
            name='types',
            field=models.CharField(choices=[('manager', 'Manager'), ('imam', 'Imam'), ('sub_imam', 'Sub Imam'), ('other', 'Other')], default='other', max_length=50, verbose_name='types'),
        ),
    ]
