# Generated by Django 4.1.13 on 2024-01-25 12:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_academic_title_employee_birth_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_user.jpg', help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
    ]
