# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd'), ('dsc', 'dsc'), ('none', 'none')], default='none', max_length=50, verbose_name='academic_degree'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('associate_professor', 'associate_professor'), ('professor', 'professor'), ('none', 'none')], default='none', max_length=50, verbose_name='academic_title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='achievement',
            field=models.CharField(blank=True, choices=[('state_awards', 'state_awards'), ('commemorative_badges', 'commemorative_badges'), ('signs', 'signs'), ('gratitude', 'gratitude'), ('compliment', 'compliment'), ('honorary_titles', 'honorary_titles'), ('diplomas_of_the_winner_of_the_exam_competition', 'diplomas_of_the_winner_of_the_exam_competition'), ('diplomas_of_competition_winners', 'diplomas_of_competition_winners'), ('international_awards', 'international_awards')], max_length=50, verbose_name='achievement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(blank=True, choices=[('medium_special', 'medium_special'), ('high', 'high'), ('none', 'none')], default='none', max_length=50, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(blank=True, choices=[('uzbek', 'uzbek'), ('russian', 'russian'), ('kazakh', 'kazakh'), ('tajik', 'tajik'), ('turkmen', 'turkmen')], default='uzbek', max_length=10, verbose_name='nation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='party',
            field=models.CharField(blank=True, choices=[('uzxdp', 'uzxdp'), ('sdp', 'sdp'), ('uzlidep', 'uzlidep'), ('uzmtdp', 'uzmtdp'), ('uzep', 'uzep'), ('none', 'none')], default='none', max_length=50, verbose_name='party'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='types',
            field=models.CharField(choices=[('manager', 'manager'), ('imam', 'imam'), ('sub_imam', 'sub_imam'), ('other', 'other')], default='other', max_length=50, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('telegram', 'telegram'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('tik_tok', 'tik_tok'), ('twitter', 'twitter'), ('youtube', 'youtube'), ('whatsapp', 'whatsapp')], max_length=30, verbose_name='social_media'),
        ),
    ]
