# Generated by Django 4.1.13 on 2023-12-09 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridayTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='files/fridaytesis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('attachment', models.FileField(blank=True, upload_to='files/attachment')),
                ('date', models.DateField()),
                ('to_imams', models.ManyToManyField(related_name='fridaytesis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juma tezisi ',
                'verbose_name_plural': 'Juma tezislari ',
            },
        ),
    ]
