# Generated by Django 4.1.13 on 2023-12-12 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
        ('friday_tesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamresult', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='tesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamresult', to='friday_tesis.fridaytesis'),
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='tesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamread', to='friday_tesis.fridaytesis'),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_district',
            field=models.ManyToManyField(blank=True, to='common.districts'),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_imams',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_region',
            field=models.ManyToManyField(to='common.regions'),
        ),
    ]
