# Generated by Django 4.1.13 on 2023-12-12 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridaytesis',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='file_bool',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='to_district',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='to_imams',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='to_region',
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='video',
        ),
        migrations.CreateModel(
            name='FridayTesisRequireds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.BooleanField(default=False)),
                ('video', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('file_bool', models.BooleanField(default=False)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesisrequireds', to='friday_tesis.fridaytesis')),
                ('to_district', models.ManyToManyField(blank=True, to='common.districts')),
                ('to_imams', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('to_region', models.ManyToManyField(to='common.regions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
