# Generated by Django 4.1.13 on 2023-12-09 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0003_fridaytesis_to_district_fridaytesis_to_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridayTesisImamRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requiredfields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='file_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/attachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='file',
            field=models.FileField(upload_to='files/fridaytesis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt'])]),
        ),
        migrations.DeleteModel(
            name='FridayTesisReqiredFields',
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='tesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requiredfields', to='friday_tesis.fridaytesis'),
        ),
    ]
