# Generated by Django 4.1.13 on 2023-12-13 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0003_remove_fridaytesis_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesis',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='file_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_district',
            field=models.ManyToManyField(blank=True, to='common.districts'),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_imams',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_region',
            field=models.ManyToManyField(blank=True, to='common.regions'),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='state',
            field=models.CharField(choices=[('1', 'Unseen'), ('2', 'Accepted'), ('3', 'Done')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/attachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'ppt'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='file',
            field=models.FileField(upload_to='files/fridaytesis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'ppt'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='file',
            field=models.FileField(blank=True, upload_to='files/tesisresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'ppt'])]),
        ),
        migrations.DeleteModel(
            name='FridayTesisRequireds',
        ),
    ]
