# Generated by Django 4.1.13 on 2023-12-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0004_fridaytesisimamread_fridaytesis_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaytesisimamread',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamread',
            name='tesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamread', to='friday_tesis.fridaytesis'),
        ),
    ]
