# Generated by Django 4.1.13 on 2023-12-13 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0004_fridaytesis_comment_fridaytesis_file_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='requirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/attachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='file',
            field=models.FileField(help_text="allowed files: ['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx']", upload_to='files/fridaytesis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='file',
            field=models.FileField(blank=True, upload_to='files/tesisresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip', 'pptx'])]),
        ),
    ]
