# Generated by Django 4.1.13 on 2023-12-11 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0005_alter_fridaytesisimamread_imam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridaytesisimamread',
            options={'verbose_name': 'Juma tezisi imom oqigan ', 'verbose_name_plural': 'Juma tezislari imom oqiganlar '},
        ),
        migrations.RemoveField(
            model_name='fridaytesis',
            name='empty',
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2002-11-11', verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridaytesisimamread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='attachment',
            field=models.FileField(blank=True, upload_to='files/attachment', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='file',
            field=models.FileField(upload_to='files/fridaytesis', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip'])]),
        ),
        migrations.CreateModel(
            name='FridayTesisImamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(blank=True, upload_to='images/tesisresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'])])),
                ('video', models.FileField(blank=True, upload_to='videos/tesisresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('comment', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='files/tesisresult', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xls', 'txt', 'zip'])])),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamresult', to=settings.AUTH_USER_MODEL)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridaytesisimamresult', to='friday_tesis.fridaytesis')),
            ],
            options={
                'verbose_name': 'Juma tezisi imom natija ',
                'verbose_name_plural': 'Juma tezislari imom natijalar ',
            },
        ),
    ]
