# Generated by Django 4.1.13 on 2023-12-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0007_alter_fridaytesis_attachment_alter_fridaytesis_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesis',
            name='type',
            field=models.CharField(choices=[('1', 'Friday'), ('2', 'Hayit')], default='1', max_length=6),
        ),
    ]
