# Generated by Django 4.1.13 on 2023-12-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0008_fridaytesis_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridaytesis',
            old_name='type',
            new_name='types',
        ),
    ]
