# Generated by Django 4.1.13 on 2023-12-19 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0010_remove_resultimages_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='man',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridaytesisimamresult',
            name='old_man',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='fridaytesisimamresult',
            unique_together={('tesis', 'imam')},
        ),
    ]
