# Generated by Django 4.1.13 on 2023-12-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0011_fridaytesisimamresult_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='child',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='man',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='old',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fridaytesisimamresult',
            name='old_man',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
