# Generated by Django 4.1.13 on 2023-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0012_alter_fridaytesisimamresult_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridaytesisimamread',
            name='seen',
        ),
    ]
