# Generated by Django 4.1.13 on 2023-12-22 05:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday_tesis', '0014_alter_fridaytesis_attachment_alter_fridaytesis_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridaytesis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Juma tezisi ', 'verbose_name_plural': 'Juma tezislari '},
        ),
        migrations.AlterModelOptions(
            name='fridaytesisimamread',
            options={'ordering': ['-created_at'], 'verbose_name': 'Juma tezisi imom oqigan ', 'verbose_name_plural': 'Juma tezislari imom oqiganlar '},
        ),
        migrations.AlterModelOptions(
            name='fridaytesisimamresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Juma tezisi imom natija ', 'verbose_name_plural': 'Juma tezislari imom natijalar '},
        ),
        migrations.AlterUniqueTogether(
            name='fridaytesisimamread',
            unique_together={('tesis', 'imam')},
        ),
    ]
