# Generated by Django 4.1.13 on 2023-12-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('friday_tesis', '0015_alter_fridaytesis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaytesis',
            name='to_region',
            field=models.ManyToManyField(to='common.regions'),
        ),
    ]
