# Generated by Django 4.1.13 on 2024-01-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('friday_tesis', '0016_alter_fridaytesis_to_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaytesis',
            name='attachment_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='file_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridaytesis',
            name='to_region',
            field=models.ManyToManyField(blank=True, to='common.regions'),
        ),
    ]
