# Generated by Django 4.1.13 on 2024-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0008_alter_mosque_mosque_heating_fuel_and_more'),
        ('friday_tesis', '0018_alter_fridaytesis_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridaytesis',
            name='to_imams',
        ),
        migrations.AddField(
            model_name='fridaytesis',
            name='to_mosque',
            field=models.ManyToManyField(blank=True, to='mosque.mosque'),
        ),
    ]
