# Generated by Django 4.1.13 on 2024-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0020_fridaythesis_fridaythesisimamread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaythesisimamread',
            name='state',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('accepted', 'Accepted'), ('done', 'Done'), ('expired', 'Expired')], default='unseen', max_length=10, verbose_name='state'),
        ),
    ]
