# Generated by Django 4.1.13 on 2024-01-25 12:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0021_alter_fridaythesisimamread_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultimages',
            options={'verbose_name': 'Natija rasmi ', 'verbose_name_plural': 'Natija rasmlari '},
        ),
        migrations.AlterModelOptions(
            name='resultvideos',
            options={'verbose_name': 'Natija videosi ', 'verbose_name_plural': 'Natija videolari '},
        ),
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='file',
            field=models.FileField(blank=True, help_text="allowed files: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']", upload_to='files/thesis_result', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip', 'pptx', 'ppt']), apps.common.validators.validate_file_size], verbose_name='file'),
        ),
    ]
