# Generated by Django 4.1 on 2024-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0023_alter_resultimages_image_alter_resultvideos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaythesis',
            name='date',
            field=models.DateField(unique=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='fridaythesisimamread',
            name='state',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('accepted', 'Accepted'), ('done', 'Done'), ('delayed', 'Delayed')], default='unseen', max_length=10, verbose_name='state'),
        ),
    ]
