# Generated by Django 4.1 on 2024-01-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0024_alter_fridaythesis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaythesisimamresult',
            name='requirement',
            field=models.BooleanField(default=False, verbose_name='requirement'),
        ),
        migrations.AddField(
            model_name='fridaythesisimamresult',
            name='state',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('accepted', 'Accepted'), ('done', 'Done'), ('delayed', 'Delayed')], default='unseen', max_length=10, verbose_name='state'),
        ),
        migrations.DeleteModel(
            name='FridayThesisImamRead',
        ),
    ]
