# Generated by Django 4.1 on 2024-02-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0025_fridaythesisimamresult_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='child',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='child'),
        ),
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='man',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='man'),
        ),
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='old',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='old'),
        ),
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='old_man',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='old_man'),
        ),
    ]
