# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday_tesis', '0026_alter_fridaythesisimamresult_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaythesis',
            name='types',
            field=models.CharField(choices=[('friday', 'friday'), ('hayit', 'hayit')], default='friday', max_length=6, verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='fridaythesisimamresult',
            name='state',
            field=models.CharField(choices=[('unseen', 'unseen'), ('accepted', 'accepted'), ('done', 'done'), ('delayed', 'delayed')], default='unseen', max_length=10, verbose_name='state'),
        ),
    ]
