# Generated by Django 4.1.13 on 2024-01-22 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mavlud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mavlud',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='mavlud',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='mavlud',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='mavlud',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
