# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavlud', '0002_alter_mavlud_comment_alter_mavlud_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mavlud',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mavlud', 'verbose_name_plural': 'Mavludlar'},
        ),
        migrations.AlterField(
            model_name='mavlud',
            name='comment',
            field=models.TextField(blank=True, verbose_name='comment'),
        ),
    ]
