# Generated by Django 4.1.13 on 2023-12-15 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireDefenceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Evacuation Road'), ('2', 'Fire Safe'), ('3', 'Fire Closet'), ('4', 'Fires Ignal'), ('5', 'Auto Fire Extinguisher')], default='1', max_length=17)),
                ('image', models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/firedefence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=355)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('built_at', models.DateField()),
                ('registered_at', models.DateField()),
                ('parking', models.BooleanField(default=False)),
                ('parking_capacity', models.IntegerField(blank=True, default=0)),
                ('basement', models.BooleanField(default=False)),
                ('second_floor', models.BooleanField(default=False)),
                ('third_floor', models.BooleanField(default=False)),
                ('cultural_heritage', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
                ('auto_fire_extinguisher', models.BooleanField(default=False)),
                ('fire_closet', models.BooleanField(default=False)),
                ('fire_signal', models.BooleanField(default=False)),
                ('service_rooms_bool', models.BooleanField(default=False)),
                ('imam_room', models.BooleanField(default=False)),
                ('sub_imam_room', models.BooleanField(default=False)),
                ('casher_room', models.BooleanField(default=False)),
                ('guard_room', models.BooleanField(default=False)),
                ('other_room', models.BooleanField(default=False)),
                ('other_room_amount', models.IntegerField(blank=True, default=0)),
                ('mosque_library', models.BooleanField(default=False)),
                ('mosque_status', models.CharField(choices=[('1', 'Good'), ('2', 'Repair'), ('3', 'Reconstruction')], default='1', max_length=17)),
                ('mosque_type', models.CharField(choices=[('1', 'Neighborhood'), ('2', 'Jome')], default='2', max_length=17)),
                ('mosque_heating_type', models.CharField(choices=[('1', 'Central'), ('2', 'Local')], default='1', max_length=17)),
                ('mosque_heating_fuel', models.CharField(choices=[('1', 'Gas'), ('2', 'Liquid Fuel'), ('3', 'Solid Fuel'), ('4', 'None')], default='4', max_length=17)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque', to='common.districts')),
                ('fire_images', models.ManyToManyField(blank=True, to='mosque.firedefenceimages')),
            ],
            options={
                'verbose_name': 'Masjid',
                'verbose_name_plural': 'Masjidlar',
            },
        ),
    ]
