# Generated by Django 4.1.13 on 2023-12-05 14:40

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('built_at', models.DateField()),
                ('registered_at', models.DateField()),
                ('mosque_status', models.CharField(choices=[('yaxshi', 'Good'), ('Tamir talab', 'Repair'), ('Qayta qurish', 'Reconstruction')], max_length=255)),
                ('mosque_type', models.CharField(choices=[('oddiy', 'Simple'), ('jome', 'Jome')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosqueAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='mosque.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MosqueAttributeOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributeoption')),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value_options', to='mosque.mosque')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
