# Generated by Django 4.1.13 on 2023-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_status',
            field=models.CharField(choices=[('Yaxshi', 'Good'), ('Tamir talab', 'Repair'), ('Qayta qurish', 'Reconstruction')], max_length=255),
        ),
    ]
