# Generated by Django 4.1.13 on 2023-12-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FireDefenceImages',
            new_name='FireDefenseImages',
        ),
    ]
