# Generated by Django 4.1.13 on 2023-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firedefenceimages',
            name='type',
            field=models.CharField(choices=[('1', 'Evacuation Road'), ('2', 'Fire Safe'), ('3', 'Fire Closet'), ('4', 'Fires Ignal'), ('5', 'Auto Fire Extinguisher')], default='1', max_length=17),
        ),
    ]
