# Generated by Django 4.1.13 on 2023-12-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0002_alter_mosque_mosque_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFireClear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(upload_to='autofireclear/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvacuationRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(upload_to='images/evacuationroad/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireCloset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(upload_to='firecloset/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireSafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(upload_to='iimage/firesafety/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FireSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('image', models.ImageField(upload_to='fire_signal/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('title', models.CharField(max_length=255)),
                ('room_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='mosqueattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='mosqueattributevalue',
            name='mosque',
        ),
        migrations.AddField(
            model_name='mosque',
            name='parking_capasity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MosqueAttributeOptionValue',
        ),
        migrations.DeleteModel(
            name='MosqueAttributeValue',
        ),
        migrations.AddField(
            model_name='room',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mosque.mosque'),
        ),
        migrations.AddField(
            model_name='firesafe',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_safes', to='mosque.mosque'),
        ),
        migrations.AddField(
            model_name='evacuationroad',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_roads', to='mosque.mosque'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='auto_fire_clear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mosque.autofireclear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='fire_closet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mosque.firecloset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='fire_signal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mosque.firesignal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosque',
            name='heritage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mosque.heritage'),
            preserve_default=False,
        ),
    ]
