# Generated by Django 4.1.13 on 2023-12-14 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0002_alter_firedefenceimages_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firedefenceimages',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/firedefence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
