# Generated by Django 4.1.13 on 2023-12-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0003_alter_firedefenseimages_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mosque',
            options={'ordering': ['-created_at'], 'verbose_name': 'Masjid', 'verbose_name_plural': 'Masjidlar'},
        ),
    ]
