# Generated by Django 4.1.13 on 2023-12-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('mosque', '0004_alter_mosque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mosque',
            name='emergency_exit_door',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='evacuation_road',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mosque_region', to='common.regions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firedefenseimages',
            name='type',
            field=models.CharField(choices=[('1', 'Evacuation Road'), ('2', 'Fire Safe'), ('3', 'Fire Closet'), ('4', 'Fire Signal'), ('5', 'Auto Fire Extinguisher'), ('6', 'Emergency Exit Door')], default='1', max_length=17),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque_district', to='common.districts'),
        ),
    ]
