# Generated by Django 4.1.13 on 2023-12-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0004_alter_firedefenceimages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firedefenceimages',
            name='type',
            field=models.CharField(choices=[('1', 'evacuation_road'), ('2', 'fire_safe'), ('3', 'fire_closet'), ('4', 'fires_ignal'), ('5', 'auto_fire_extinguisher')], default='1', max_length=17),
        ),
    ]
