# Generated by Django 4.1.13 on 2023-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0005_alter_firedefenceimages_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='mosque_heating_fuel',
            field=models.CharField(choices=[('1', 'Gas'), ('2', 'Liquid Fuel'), ('3', 'Solid Fuel'), ('4', 'None')], default='4', max_length=17),
        ),
        migrations.AddField(
            model_name='mosque',
            name='mosque_heating_type',
            field=models.CharField(choices=[('1', 'Central'), ('2', 'Local')], default='1', max_length=17),
        ),
        migrations.AddField(
            model_name='mosque',
            name='mosque_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_status',
            field=models.CharField(choices=[('1', 'Good'), ('2', 'Repair'), ('3', 'Reconstruction')], default='1', max_length=17),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_type',
            field=models.CharField(choices=[('1', 'Neighborhood'), ('2', 'Jome')], default='2', max_length=17),
        ),
    ]
