# Generated by Django 4.1.13 on 2024-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0007_mosque_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_heating_fuel',
            field=models.CharField(blank=True, choices=[('1', 'Gas'), ('2', 'Liquid Fuel'), ('3', 'Solid Fuel'), ('4', 'None')], max_length=17),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_heating_type',
            field=models.CharField(blank=True, choices=[('1', 'Central'), ('2', 'Local')], max_length=17),
        ),
    ]
