# Generated by Django 4.1.13 on 2024-01-22 09:10

import apps.common.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_districts_name_alter_districts_region_and_more'),
        ('mosque', '0008_alter_mosque_mosque_heating_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firedefenseimages',
            name='image',
            field=models.ImageField(help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/fire_defense/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='firedefenseimages',
            name='type',
            field=models.CharField(choices=[('evacuation_road', 'Evacuation Road'), ('fire_safe', 'Fire Safe'), ('fire_closet', 'Fire Closet'), ('fire_signal', 'Fire Signal'), ('auto_fire_extinguisher', 'Auto Fire Extinguisher'), ('emergency_exit_door', 'Emergency Exit Door')], default='evacuation_road', max_length=22, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='address',
            field=models.CharField(max_length=355, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='auto_fire_extinguisher',
            field=models.BooleanField(default=False, verbose_name='auto_fire_extinguisher'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='basement',
            field=models.BooleanField(default=False, verbose_name='basement'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='built_at',
            field=models.DateField(verbose_name='built_at'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='casher_room',
            field=models.BooleanField(default=False, verbose_name='casher_room'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='cultural_heritage',
            field=models.BooleanField(default=False, verbose_name='cultural_heritage'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque_district', to='common.districts', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='emergency_exit_door',
            field=models.BooleanField(default=False, verbose_name='emergency_exit_door'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='evacuation_road',
            field=models.BooleanField(default=False, verbose_name='evacuation_road'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='fire_closet',
            field=models.BooleanField(default=False, verbose_name='fire_closet'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='fire_images',
            field=models.ManyToManyField(blank=True, to='mosque.firedefenseimages', verbose_name='fire_images'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='fire_safety',
            field=models.BooleanField(default=False, verbose_name='fire_safety'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='fire_signal',
            field=models.BooleanField(default=False, verbose_name='fire_signal'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='graveyard',
            field=models.BooleanField(default=False, verbose_name='graveyard'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='guard_room',
            field=models.BooleanField(default=False, verbose_name='guard_room'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_mosque.png', help_text="allowed images: ['jpg', 'jpeg', 'png', 'svg']", upload_to='images/mosque/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg']), apps.common.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='imam_room',
            field=models.BooleanField(default=False, verbose_name='imam_room'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_heating_fuel',
            field=models.CharField(blank=True, choices=[('gas', 'Gas'), ('liquid_fuel', 'Liquid Fuel'), ('solid_fuel', 'Solid Fuel'), ('none', 'None')], max_length=17, verbose_name='mosque_heating_fuel'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_heating_type',
            field=models.CharField(blank=True, choices=[('central', 'Central'), ('local', 'Local')], max_length=17, verbose_name='mosque_heating_type'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_library',
            field=models.BooleanField(default=False, verbose_name='mosque_library'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_status',
            field=models.CharField(choices=[('good', 'Good'), ('repair', 'Repair'), ('reconstruction', 'Reconstruction')], default='good', max_length=17, verbose_name='mosque_status'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='mosque_type',
            field=models.CharField(choices=[('neighborhood', 'Neighborhood'), ('jame', 'Jame')], default='jame', max_length=17, verbose_name='mosque_type'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='other_room',
            field=models.BooleanField(default=False, verbose_name='other_room'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='other_room_amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='other_room_amount'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='parking_capacity',
            field=models.IntegerField(blank=True, default=0, verbose_name='parking_capacity'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosque_region', to='common.regions', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='registered_at',
            field=models.DateField(verbose_name='registered_at'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='second_floor',
            field=models.BooleanField(default=False, verbose_name='second_floor'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='service_rooms_bool',
            field=models.BooleanField(default=False, verbose_name='service_rooms_bool'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='shop',
            field=models.BooleanField(default=False, verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='shrine',
            field=models.BooleanField(default=False, verbose_name='shrine'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='sub_imam_room',
            field=models.BooleanField(default=False, verbose_name='sub_imam_room'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='third_floor',
            field=models.BooleanField(default=False, verbose_name='third_floor'),
        ),
    ]
