# Generated by Django 4.1.13 on 2024-01-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0009_alter_firedefenseimages_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firedefenseimages',
            options={'verbose_name': 'Masjid rasmi ', 'verbose_name_plural': 'Masjid rasmlari '},
        ),
    ]
