# Generated by Django 4.1 on 2024-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0011_serviceroom_remove_mosque_casher_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='basement',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='second_floor',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='third_floor',
        ),
        migrations.AddField(
            model_name='mosque',
            name='floor',
            field=models.CharField(blank=True, choices=[('ground', 'ground'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=15, null=True, verbose_name='floor'),
        ),
    ]
