# Generated by Django 4.1.13 on 2023-12-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_prayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicprayers',
            options={'verbose_name': 'Jamoat namozi ', 'verbose_name_plural': 'Jamoat namozlari '},
        ),
        migrations.RemoveField(
            model_name='publicprayers',
            name='prayer',
        ),
        migrations.AddField(
            model_name='publicprayers',
            name='prayer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='public_prayers.prayers'),
            preserve_default=False,
        ),
    ]
