# Generated by Django 4.1.13 on 2023-12-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_prayers', '0002_alter_publicprayers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprayers',
            name='prayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayers', to='public_prayers.prayers'),
        ),
    ]
