# Generated by Django 4.1.13 on 2023-12-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_prayers', '0003_alter_publicprayers_prayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprayers',
            name='prayer',
        ),
        migrations.AddField(
            model_name='publicprayers',
            name='prayer',
            field=models.ManyToManyField(related_name='prayers', to='public_prayers.prayers'),
        ),
    ]
