# Generated by Django 4.1.13 on 2024-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_prayers', '0004_remove_publicprayers_prayer_publicprayers_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayers',
            name='label',
            field=models.CharField(default='bomdod', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prayers',
            name='name',
            field=models.SlugField(max_length=255),
        ),
    ]
