# Generated by Django 4.1.13 on 2024-01-22 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_prayers', '0005_prayers_label_alter_prayers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayers',
            options={'verbose_name': 'Namoz vaqti ', 'verbose_name_plural': 'Namoz vaqtlari '},
        ),
        migrations.AlterModelOptions(
            name='publicprayers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jamoat namozi ', 'verbose_name_plural': 'Jamoat namozlari '},
        ),
        migrations.AlterField(
            model_name='prayers',
            name='label',
            field=models.CharField(max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='prayers',
            name='name',
            field=models.SlugField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='publicprayers',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imam_prayers', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='publicprayers',
            name='prayer',
            field=models.ManyToManyField(related_name='prayers', to='public_prayers.prayers', verbose_name='prayer'),
        ),
    ]
