# Generated by Django 4.1.13 on 2023-12-16 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('type', models.CharField(choices=[('1', 'Educational Institution'), ('2', 'Prison'), ('3', 'Military Unit'), ('4', 'Other')], max_length=18)),
                ('institution_type', models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Middle'), ('3', 'General')], max_length=10, null=True)),
                ('participant_type', models.CharField(blank=True, choices=[('1', 'Employee'), ('2', 'Student'), ('3', 'School Student'), ('4', 'Other')], max_length=14, null=True)),
                ('prisoner_type', models.CharField(blank=True, choices=[('1', 'Law 159'), ('2', 'Law 244'), ('3', 'Young'), ('4', 'Minor'), ('5', 'Other')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('imam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tashkilot ',
                'verbose_name_plural': 'Tashkilotlar ',
            },
        ),
    ]
