# Generated by Django 4.1.13 on 2024-01-22 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='imam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='imam'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('middle', 'Middle'), ('general', 'General')], max_length=10, null=True, verbose_name='institution_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('student', 'Student'), ('school_student', 'School Student'), ('other', 'Other')], max_length=14, null=True, verbose_name='participant_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='prisoner_type',
            field=models.CharField(blank=True, choices=[('law_159', 'Law 159'), ('law_244', 'Law 244'), ('young', 'Young'), ('minor', 'Minor'), ('other', 'Other')], max_length=10, null=True, verbose_name='prisoner_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('educational_institution', 'Educational Institution'), ('prison', 'Prison'), ('military_unit', 'Military Unit'), ('other', 'Other')], max_length=23, verbose_name='type'),
        ),
    ]
