# Generated by Django 4.1.13 on 2024-01-29 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tashkilot ', 'verbose_name_plural': 'Tashkilotlar '},
        ),
    ]
