# Generated by Django 4.1 on 2024-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('middle', 'middle'), ('general', 'general')], max_length=10, null=True, verbose_name='institution_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='participant_type',
            field=models.CharField(blank=True, choices=[('employee', 'employee'), ('student', 'student'), ('school_student', 'school_student'), ('other', 'other')], max_length=14, null=True, verbose_name='participant_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='prisoner_type',
            field=models.CharField(blank=True, choices=[('law_159', 'law_159'), ('law_244', 'law_244'), ('young', 'young'), ('minor', 'minor'), ('other', 'other')], max_length=10, null=True, verbose_name='prisoner_type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('educational_institution', 'educational_institution'), ('prison', 'prison'), ('military_unit', 'military_unit'), ('other', 'other')], max_length=23, verbose_name='type'),
        ),
    ]
